### ISSUE TITLE
missing file

### ISSUE THREAD

**Issue by matphillips** [geeksville/AutoWifi#1]
Very interesting solution, I'm going to dig into the Espressif code to see what's going on behind the scenes.

For those using the Arduino framework, this library won't import due to not having a library.properties file.

@geeksville could you add a file at the same level as library.json, called library.properties and populate it with something like the below please?

```
name=AutoWifi
version=0.1.0
author=Kevin Hester
maintainer=Geeksville
sentence=ESP32 Wifi config
paragraph=Making ESP32 wifi setup trivial with SmartConfig Android/iOS helper apps.
category=Device Control
url=https://github.com/geeksville/AutoWifi.git
architectures=esp32
includes=none
```

**Comment by geeksville** [comment]
ooh thanks!  I'll add that now
